export const locationData = [  
  {
    initial: 'A',
    list: [
      {
        title: 'Abia',
        list: [
          'Aba North',
          'Aba South',
          'Arochukwu',
          'Bende',
          'Ikwuano',
          'Isiala Ngwa North',
          'Isiala Ngwa South',
          'Isuikwuato',
          'Obi Ngwa',
          'Ohafia',
          'Osisioma Ngwa',
          'Ugwunagbo',
          'Ukwa East',
          'Ukwa West',
          'Umuahia North',
          'Umuahia South',
          'Umu Nneochi',
        ],
      },
      {
        title: 'Adamawa',
        list: [
          'Demsa',
          'Fufore',
          'Ganye',
          'Girei',
          'Gombi',
          'Guyuk',
          'Hong',
          'Jada',
          'Lamurde',
          'Madagali',
          'Maiha',
          'Mayo-Belwa',
          'Michika',
          'Mubi North',
          'Mubi South',
          'Numan',
          'Shelleng',
          'Song',
          'Toungo',
          'Yola North',
          'Yola South',
        ],
      },
      {
        title: 'Akwa Ibom',
        list: [
          'Abak',
          'Eastern Obolo',
          'Eket',
          'Esit Eket',
          'Essien Udim',
          'Etim Ekpo',
          'Etinan',
          'Ibeno',
          'Ibesikpo Asutan',
          'Ibiono Ibom',
          'Ika',
          'Ikono',
          'Ikot Abasi',
          'Ikot Ekpene',
          'Ini',
          'Itu',
          'Mbo',
          'Mkpat Enin',
          'Nsit Atai',
          'Nsit Ibom',
          'Nsit Ubium',
          'Obot Akara',
          'Okobo',
          'Onna',
          'Oron',
          'Oruk Anam',
          'Udung Uko',
          'Ukanafun',
          'Uruan',
          'Urue-Offong Oruko',
          'Uyo',
        ],
      },
      {
        title: 'Anambra',
        list: [
          'Aguata',
          'Awka North',
          'Awka South',
          'Anambra East',
          'Anambra West',
          'Anaocha',
          'Ayamelum',
          'Dunukofia',
          'Ekwusigo',
          'Idemili North',
          'Idemili South',
          'Ihiala',
          'Njikoka',
          'Nnewi North',
          'Nnewi South',
          'Ogbaru',
          'Onitsha North',
          'Onitsha South',
          'Orumba North',
          'Orumba South',
          'Oyi',
        ],
      },
    ],
  },
  {
    initial: 'B',
    list: [
      {
        title: 'Bauchi',
        list: [
          'Alkaleri',
          'Bauchi',
          'Bogoro',
          'Damban',
          'Darazo',
          'Dass',
          'Ganjuwa',
          'Giade',
          'Itas/Gadau',
          'Jama\'are',
          'Katagum',
          'Kirfi',
          'Misau',
          'Ningi',
          'Shira',
          'Tafawa Balewa',
          'Toro',
          'Warji',
          'Zaki',
        ],
      },
      {
        title: 'Bayelsa',
        list: [
          'Brass',
          'Ekeremor',
          'Kolokuma/Opokuma',
          'Nembe',
          'Ogbia',
          'Sagbama',
          'Southern Ijaw',
          'Yenagoa',
        ],
      },
      {
        title: 'Benue',
        list: [
          'Ado',
          'Agatu',
          'Apa',
          'Buruku',
          'Gboko',
          'Guma',
          'Gwer East',
          'Gwer West',
          'Katsina-Ala',
          'Konshisha',
          'Kwande',
          'Logo',
          'Makurdi',
          'Obi',
          'Ogbadibo',
          'Ohimini',
          'Oju',
          'Okpokwu',
          'Oturkpo',
          'Tarka',
          'Ukum',
          'Ushongo',
          'Vandeikya',
        ],
      },
      {
        title: 'Borno',
        list: [
          'Abadam',
          'Askira/Uba',
          'Bama',
          'Bayo',
          'Biu',
          'Chibok',
          'Damboa',
          'Dikwa',
          'Gubio',
          'Guzamala',
          'Gwoza',
          'Hawul',
          'Jere',
          'Kaga',
          'Kala/Balge',
          'Konduga',
          'Kukawa',
          'Kwaya Kusar',
          'Mafa',
          'Magumeri',
          'Maiduguri',
          'Marte',
          'Mobbar',
          'Monguno',
          'Ngala',
          'Nganzai',
          'Shani',
        ],
      },
    ],
  },
  {
    initial: 'C',
    list: [
      {
        title: 'Cross River',
        list: [
          'Abi',
          'Akamkpa',
          'Akpabuyo',
          'Bakassi',
          'Bekwarra',
          'Biase',
          'Boki',
          'Calabar Municipal',
          'Calabar South',
          'Etung',
          'Ikom',
          'Obanliku',
          'Obubra',
          'Obudu',
          'Odukpani',
          'Ogoja',
          'Yakuur',
          'Yala',
        ],
      },
    ],
  },
  {
    initial: 'D',
    list: [
      {
        title: 'Delta',
        list: [
          'Aniocha North',
          'Aniocha South',
          'Bomadi',
          'Burutu',
          'Ethiope East',
          'Ethiope West',
          'Ika North East',
          'Ika South',
          'Isoko North',
          'Isoko South',
          'Ndokwa East',
          'Ndokwa West',
          'Okpe',
          'Oshimili North',
          'Oshimili South',
          'Patani',
          'Sapele',
          'Udu',
          'Ughelli North',
          'Ughelli South',
          'Ukwuani',
          'Uvwie',
          'Warri North',
          'Warri South',
          'Warri South West',
        ],
      },
    ],
  },
  {
    initial: 'E',
    list: [
      {
        title: 'Ebonyi',
        list: [
          'Abakaliki',
          'Afikpo North',
          'Afikpo South',
          'Ebonyi',
          'Ezza North',
          'Ezza South',
          'Ikwo',
          'Ishielu',
          'Ivo',
          'Izzi',
          'Ohaozara',
          'Ohaukwu',
          'Onicha',
        ],
      },
      {
        title: 'Edo',
        list: [
          'Akoko-Edo',
          'Egor',
          'Esan Central',
          'Esan North-East',
          'Esan South-East',
          'Esan West',
          'Etsako Central',
          'Etsako East',
          'Etsako West',
          'Igueben',
          'Ikpoba Okha',
          'Orhionmwon',
          'Oredo',
          'Ovia North-East',
          'Ovia South-West',
          'Owan East',
          'Owan West',
          'Uhunmwonde',
        ],
      },
      {
        title: 'Ekiti',
        list: [
          'Ado Ekiti',
          'Efon',
          'Ekiti East',
          'Ekiti South-West',
          'Ekiti West',
          'Emure',
          'Gbonyin',
          'Ido Osi',
          'Ijero',
          'Ikere',
          'Ikole',
          'Ilejemeje',
          'Irepodun/Ifelodun',
          'Ise/Orun',
          'Moba',
          'Oye',
        ],
      },
      {
        title: 'Enugu',
        list: [
          'Aninri',
          'Awgu',
          'Enugu East',
          'Enugu North',
          'Enugu South',
          'Ezeagu',
          'Igbo Etiti',
          'Igbo Eze North',
          'Igbo Eze South',
          'Isi Uzo',
          'Nkanu East',
          'Nkanu West',
          'Nsukka',
          'Oji River',
          'Udenu',
          'Udi',
          'Uzo-Uwani',
        ],
      },
    ],
  },
  {
    initial: 'G',
    list: [
      {
        title: 'Gombe',
        list: [
          'Akko',
          'Balanga',
          'Billiri',
          'Dukku',
          'Funakaye',
          'Gombe',
          'Kaltungo',
          'Kwami',
          'Nafada',
          'Shongom',
          'Yamaltu/Deba',
        ],
      },
    ],
  },
  {
    initial: 'I',
    list: [
      {
        title: 'Imo',
        list: [
          'Aboh Mbaise',
          'Ahiazu Mbaise',
          'Ehime Mbano',
          'Ezinihitte Mbaise',
          'Ideato North',
          'Ideato South',
          'Ihitte/Uboma',
          'Ikeduru',
          'Isiala Mbano',
          'Isu',
          'Mbaitoli',
          'Ngor Okpala',
          'Njaba',
          'Nkwerre',
          'Nwangele',
          'Obowo',
          'Oguta',
          'Ohaji/Egbema',
          'Okigwe',
          'Orlu',
          'Orsu',
          'Oru East',
          'Oru West',
          'Owerri Municipal',
          'Owerri North',
          'Owerri West',
          'Unuimo',
        ],
      },
    ],
  },
  {
    initial: 'J',
    list: [
      {
        title: 'Jigawa',
        list: [
          'Auyo',
          'Babura',
          'Biriniwa',
          'Birnin Kudu',
          'Buji',
          'Dutse',
          'Gagarawa',
          'Garki',
          'Gumel',
          'Guri',
          'Gwaram',
          'Gwiwa',
          'Hadejia',
          'Jahun',
          'Kafin Hausa',
          'Kaugama',
          'Kazaure',
          'Kiri Kasama',
          'Kiyawa',
          'Kaugama',
          'Maigatari',
          'Malam Madori',
          'Miga',
          'Ringim',
          'Roni',
          'Sule Tankarkar',
          'Taura',
          'Yankwashi',
        ],
      },
    ],
  },
  {
    initial: 'K',
    list: [
      {
        title: 'Kaduna',
        list: [
          'Birnin Gwari',
          'Chikun',
          'Giwa',
          'Igabi',
          'Ikara',
          'Jaba',
          'Jema\'a',
          'Kachia',
          'Kaduna North',
          'Kaduna South',
          'Kagoro',
          'Kajuru',
          'Kaura',
          'Kauru',
          'Kubau',
          'Kudan',
          'Lere',
          'Makarfi',
          'Sabon Gari',
          'Sanga',
          'Soba',
          'Zangon Kataf',
          'Zaria',
        ],
      },
      {
        title: 'Kano',
        list: [
          'Ajingi',
          'Albasu',
          'Bagwai',
          'Bebeji',
          'Bichi',
          'Bunkure',
          'Dala',
          'Dambatta',
          'Dawakin Kudu',
          'Dawakin Tofa',
          'Doguwa',
          'Fagge',
          'Gabasawa',
          'Garko',
          'Garun Mallam',
          'Gaya',
          'Gezawa',
          'Gwale',
          'Gwarzo',
          'Kabo',
          'Kano Municipal',
          'Karaye',
          'Kibiya',
          'Kiru',
          'Kumbotso',
          'Kunchi',
          'Kura',
          'Madobi',
          'Makoda',
          'Minjibir',
          'Nasarawa',
          'Rano',
          'Rimin Gado',
          'Rogo',
          'Shanono',
          'Sumaila',
          'Takai',
          'Tarauni',
          'Tofa',
          'Tsanyawa',
          'Tudun Wada',
          'Ungogo',
          'Warawa',
          'Wudil',
        ],
      },
      {
        title: 'Katsina',
        list: [
          'Bakori',
          'Batagarawa',
          'Batsari',
          'Baure',
          'Bindawa',
          'Charanchi',
          'Dan Musa',
          'Dandume',
          'Danja',
          'Daura',
          'Dutsi',
          'Dutsin-Ma',
          'Faskari',
          'Funtua',
          'Ingawa',
          'Jibia',
          'Kafur',
          'Kaita',
          'Kankara',
          'Kankia',
          'Katsina',
          'Kurfi',
          'Kusada',
          'Mai\'Adua',
          'Malumfashi',
          'Mani',
          'Mashi',
          'Matazu',
          'Musawa',
          'Rimi',
          'Sabuwa',
          'Safana',
          'Sandamu',
          'Zango',
        ],
      },
      {
        title: 'Kebbi',
        list: [
          'Aleiro',
          'Arewa Dandi',
          'Argungu',
          'Augie',
          'Bagudo',
          'Birnin Kebbi',
          'Bunza',
          'Dandi',
          'Fakai',
          'Gwandu',
          'Jega',
          'Kalgo',
          'Koko/Besse',
          'Maiyama',
          'Ngaski',
          'Sakaba',
          'Shanga',
          'Suru',
          'Wasagu/Danko',
          'Yauri',
          'Zuru',
        ],
      },
      {
        title: 'Kogi',
        list: [
          'Adavi',
          'Ajaokuta',
          'Ankpa',
          'Bassa',
          'Dekina',
          'Ibaji',
          'Idah',
          'Igalamela Odolu',
          'Ijumu',
          'Kabba/Bunu',
          'Kogi',
          'Lokoja',
          'Mopa Muro',
          'Ofu',
          'Ogori/Magongo',
          'Okehi',
          'Okene',
          'Olamaboro',
          'Omala',
          'Yagba East',
          'Yagba West',
        ],
      },
      {
        title: 'Kwara',
        list: [
          'Asa',
          'Baruten',
          'Edu',
          'Ekiti',
          'Ifelodun',
          'Ilorin East',
          'Ilorin South',
          'Ilorin West',
          'Irepodun',
          'Isin',
          'Kaiama',
          'Moro',
          'Offa',
          'Oke Ero',
          'Oyun',
          'Pategi',
        ],
      },
    ],
  },
  {
    initial: 'L',
    list: [
      {
        title: 'Lagos',
        list: [
          'Agege',
          'Ajeromi-Ifelodun',
          'Alimosho',
          'Amuwo-Odofin',
          'Apapa',
          'Badagry',
          'Epe',
          'Eti Osa',
          'Ibeju-Lekki',
          'Ifako-Ijaiye',
          'Ikeja',
          'Ikorodu',
          'Kosofe',
          'Lagos Island',
          'Lagos Mainland',
          'Mushin',
          'Ojo',
          'Oshodi-Isolo',
          'Shomolu',
          'Surulere',
        ],
      },
    ],
  },
  {
    initial: 'N',
    list: [
      {
        title: 'Nasarawa',
        list: [
          'Akwanga',
          'Awe',
          'Doma',
          'Karu',
          'Keana',
          'Keffi',
          'Kokona',
          'Lafia',
          'Nasarawa',
          'Nasarawa-Eggon',
          'Obi',
          'Toto',
          'Wamba',
        ],
      },
      {
        title: 'Niger',
        list: [
          'Agaie',
          'Agwara',
          'Bida',
          'Borgu',
          'Bosso',
          'Chanchaga',
          'Edati',
          'Gbako',
          'Gurara',
          'Katcha',
          'Kontagora',
          'Lapai',
          'Lavun',
          'Magama',
          'Mariga',
          'Mashegu',
          'Mokwa',
          'Moya',
          'Paikoro',
          'Rafi',
          'Rijau',
          'Shiroro',
          'Suleja',
          'Tafa',
          'Wushishi',
        ],
      },
    ],
  },
  {
    initial: 'O',
    list: [
      {
        title: 'Ogun',
        list: [
          'Abeokuta North',
          'Abeokuta South',
          'Ado-Odo/Ota',
          'Egbado North',
          'Egbado South',
          'Ewekoro',
          'Ifo',
          'Ijebu East',
          'Ijebu North',
          'Ijebu North East',
          'Ijebu Ode',
          'Ikenne',
          'Imeko-Afon',
          'Ipokia',
          'Obafemi-Owode',
          'Odeda',
          'Odogbolu',
          'Ogun Waterside',
          'Remo North',
          'Shagamu',
        ],
      },
      {
        title: 'Ondo',
        list: [
          'Akoko North-East',
          'Akoko North-West',
          'Akoko South-West',
          'Akoko South-East',
          'Akure North',
          'Akure South',
          'Ese Odo',
          'Idanre',
          'Ifedore',
          'Ilaje',
          'Ile Oluji/Okeigbo',
          'Irele',
          'Odigbo',
          'Okitipupa',
          'Ondo East',
          'Ondo West',
          'Ose',
          'Owo',
        ],
      },
      {
        title: 'Osun',
        list: [
          'Atakumosa East',
          'Atakumosa West',
          'Aiyedire',
          'Boluwaduro',
          'Boripe',
          'Ede North',
          'Ede South',
          'Ife Central',
          'Ife East',
          'Ife North',
          'Ife South',
          'Egbedore',
          'Ejigbo',
          'Ifedayo',
          'Ifelodun',
          'Ila',
          'Ilesa East',
          'Ilesa West',
          'Irepodun',
          'Irewole',
          'Isokan',
          'Iwo',
          'Obokun',
          'Odo Otin',
          'Ola Oluwa',
          'Olorunda',
          'Oriade',
          'Orolu',
          'Osogbo',
        ],
      },
    ],
  },
  {
    initial: 'P',
    list: [
      {
        title: 'Plateau',
        list: [
          'Barkin Ladi',
          'Bassa',
          'Bokkos',
          'Jos East',
          'Jos North',
          'Jos South',
          'Kanam',
          'Kanke',
          'Langtang North',
          'Langtang South',
          'Mangu',
          'Mikang',
          'Pankshin',
          'Qua\'an Pan',
          'Riyom',
          'Shendam',
          'Wase',
        ],
      },
    ],
  },
  {
    initial: 'R',
    list: [
      {
        title: 'Rivers',
        list: [
          'Abua/Odual',
          'Ahoada East',
          'Ahoada West',
          'Akuku-Toru',
          'Andoni',
          'Asari-Toru',
          'Bonny',
          'Degema',
          'Emohua',
          'Eleme',
          'Etche',
          'Gokana',
          'Ikwerre',
          'Khana',
          'Obio/Akpor',
          'Ogba/Egbema/Ndoni',
          'Ogu/Bolo',
          'Okrika',
          'Omuma',
          'Opobo/Nkoro',
          'Oyigbo',
          'Port Harcourt',
          'Tai',
        ],
      },
    ],
  },
  {
    initial: 'S',
    list: [
      {
        title: 'Sokoto',
        list: [
          'Binji',
          'Bodinga',
          'Dange-Shuni',
          'Gada',
          'Goronyo',
          'Gudu',
          'Gwadabawa',
          'Illela',
          'Isa',
          'Kebbe',
          'Kware',
          'Rabah',
          'Sabon Birni',
          'Shagari',
          'Silame',
          'Sokoto North',
          'Sokoto South',
          'Tambuwal',
          'Tangaza',
          'Tureta',
          'Wamako',
          'Wurno',
          'Yabo',
        ],
      },
    ],
  },
  {
    initial: 'T',
    list: [
      {
        title: 'Taraba',
        list: [
          'Ardo Kola',
          'Bali',
          'Donga',
          'Gashaka',
          'Gassol',
          'Ibi',
          'Jalingo',
          'Karim Lamido',
          'Kumi',
          'Lau',
          'Sardauna',
          'Takum',
          'Ussa',
          'Wukari',
          'Yorro',
          'Zing',
        ],
      },
    ],
  },
  {
    initial: 'Y',
    list: [
      {
        title: 'Yobe',
        list: [
          'Bade',
          'Bursari',
          'Damaturu',
          'Fika',
          'Fune',
          'Geidam',
          'Gujba',
          'Gulani',
          'Jakusko',
          'Karasuwa',
          'Machina',
          'Nangere',
          'Nguru',
          'Potiskum',
          'Tarmuwa',
          'Yunusari',
          'Yusufari',
        ],
      },
    ],
  },
  {
    initial: 'Z',
    list: [
      {
        title: 'Zamfara',
        list: [
          'Anka',
          'Bakura',
          'Birnin Magaji/Kiyaw',
          'Bukkuyum',
          'Bungudu',
          'Gummi',
          'Gusau',
          'Kaura Namoda',
          'Maradun',
          'Maru',
          'Shinkafi',
          'Talata Mafara',
          'Chafe',
          'Zurmi',
        ],
      },
    ],
  }
]